const menuList = [
    {
        title:'首页',//菜单标题名称
        key:'/home',//对应的path
        icon:'home',//图标名称
        isPublic:true
    },
    {
        title:'商品',
        key:'/products',
        icon:'appstore',
        children:[//子菜单列表
            {
                title:'品类管理',
                key:'/category',
                icon:'bars'
            },
            {
                title:'商品管理',
                key:'/product',
                icon:'credit-card'
            }
        ]
    },
    {
        title:'用户管理',//菜单标题名称
        key:'/user',//对应的path
        icon:'user'//图标名称
    },
    {
        title:'角色管理',//菜单标题名称
        key:'/role',//对应的path
        icon:'solution'//图标名称
    },
    {
        title:'图形图表',
        key:'/charts',
        icon:'area-chart',
        children:[//子菜单列表
            {
                title:'柱形图',
                key:'/charts/bar',
                icon:'bar-chart'
            },
            {
                title:'折线图',
                key:'/charts/line',
                icon:'line-chart'
            },
            {
                title:'饼图',
                key:'/charts/pie',
                icon:'pie-chart'
            }
        ]
    },
    {
        title:'学习工具',
        key:'/learnTools',
        icon:'plus',
        children:[//子菜单列表
            {
                title:'思维导图',
                key:'/learnTools/mind',
                icon:'retweet'
            },
            {
                title:'流程图',
                key:'/learnTools/flow',
                icon:'retweet'
            },
            {
                title:'拓扑图',
                key:'/learnTools/koni',
                icon:'retweet'
            }
        ]
    },
];

export default menuList;